apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka-service

spec:
  type: LoadBalancer
  ports:
    - targetPort: 9092
      port: 9092
  selector:
    name: kafka-pod
          #    app: kafka
